name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: paradoxdruid/fealden:version1.0
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest python-dotenv coverage
      - name: Coverage and tests
        run: |
          coverage run -m pytest && coverage xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
